
runtime: nodejs12 # or nodejs10

instance_class: F2

env_variables:
  SQL_USER: root
  SQL_PASSWORD: lpiP7kP36BrJK4m8
  SQL_DATABASE: takas
  INSTANCE_CONNECTION_NAME: takas-300716:us-east1:takas
  
beta_settings:
  cloud_sql_instances: takas-300716:us-east1:takas

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

inbound_services:
  - warmup