
runtime: nodejs12 # or nodejs10

instance_class: F2

env_variables:
  SQL_USER: root
  SQL_PASSWORD: hg7O4bfmJNuip7cy
  SQL_DATABASE: merkarapid
  INSTANCE_CONNECTION_NAME: merkarapid-api:us-east1:merkarapid
  
beta_settings:
  cloud_sql_instances: merkarapid-api:us-east1:merkarapid

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

inbound_services:
  - warmup