
runtime: nodejs # or nodejs12

# instance_class: F2
env: flex

env_variables:
  DB_USER: root
  DB_PASS: lpiP7kP36BrJK4m8
  DB_NAME: takas
  CLOUD_SQL_CONNECTION_NAME: takas-300716:us-east1:takas

skip_files: 
  .env

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
  
beta_settings:
  cloud_sql_instances: takas-300716:us-east1:takas

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

inbound_services:
  - warmup

network:
  forwarded_ports: 
    - 65080
  instance_tag: websocket  
  session_affinity: true 